auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: danyangzhao.com
url: http://danyangzhao.com/
feed: /atom.xml
author_info: <a href="http://danyangzhao.com//">Danyang</a>
